name: Windows CI

on:
  push:
    branches: [master]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  cmake:
    name: CMake - MSVC ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        include:
          - platform: x64
            runner: windows-latest
          - platform: win32
            runner: windows-latest
          - platform: ARM64
            runner: windows-11-arm

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Build in Release Mode
        continue-on-error: true
        run: |
          cmake -S . -B Release -A ${{ matrix.platform }}
          cmake --build Release --config Release

      - name: Build in Debug Mode
        run: |
          cmake -S. -B Debug `
            -A ${{ matrix.platform }} `
            -DENABLE_ASAN=ON `
            -DENABLE_UBSAN=ON
          cmake --build Debug --config Debug

      - name: Run Tests (Debug)
        run: ctest --test-dir Debug --build-config Debug --output-on-failure
